export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:3001';

export const ENDPOINTS = {
  AUTH: {
    LOGIN:   '/auth/login',
    LOGOUT:  '/auth/logout',
    REFRESH: '/auth/refresh',
    PROFILE: '/auth/profile',
    GOOGLE_CALLBACK: '/auth/google/callback',
  },
  USERS: {
    LIST:   '/users',
    DETAIL: (id) => `/users/${id}`,
    ME:     '/users/me',
  },
  AGENTS: {
    SUBSCRIPTIONS: '/agents/subscriptions',
  },
  FINANCIAL: {
    OVERVIEW:       '/financial/overview',
    TRANSACTIONS:   '/financial/transactions',
    TRANSACTION:    (id) => `/financial/transactions/${id}`,
    CATEGORIES:     '/financial/categories',
    SAVINGS_GOALS:  '/financial/savings-goals',
    SAVINGS_GOAL:   (id) => `/financial/savings-goals/${id}`,
    INVESTMENTS:    '/financial/investments',
    REPORTS:        '/financial/reports',
    GMAIL_CONNECT:        '/financial/gmail/connect',
    GMAIL_DISCONNECT:     '/financial/gmail/disconnect',
    GMAIL_SYNC:           '/financial/gmail/sync',
    GMAIL_STATUS:         '/financial/gmail/status',
    GMAIL_ACCOUNTS:       '/financial/gmail/accounts',
    GMAIL_ACCOUNT:        (id) => `/financial/gmail/accounts/${id}`,
    GMAIL_ACCOUNT_SYNC:   (id) => `/financial/gmail/accounts/${id}/sync`,
    GMAIL_ACCOUNT_RESYNC: (id) => `/financial/gmail/accounts/${id}/resync`,
    OVERVIEW_COMBINED:    '/financial/overview/combined',
    OVERVIEW_BY_BANK:     '/financial/overview/by-bank',
    PDF_UPLOAD:     '/financial/statements/upload',
    ANALYSIS:       '/financial/analysis',
    INSIGHTS:       '/financial/insights',
    LEDGER:              '/financial/ledger',
    LEDGER_ENTRY:        (id) => `/financial/ledger/${id}`,
    LEDGER_PAYMENT:      (id) => `/financial/ledger/${id}/payment`,
    LEDGER_SETTLE:       (id) => `/financial/ledger/${id}/settle`,
    LEDGER_WRITE_OFF:    (id) => `/financial/ledger/${id}/write-off`,
    LEDGER_SUMMARY:      '/financial/ledger/summary',
    ALLOCATIONS:         '/financial/allocations',
    ALLOCATION_ENTRY:    (id) => `/financial/allocations/${id}`,
    ALLOCATION_TOP_UP:   (id) => `/financial/allocations/${id}/top-up`,
    ALLOCATION_MARK_USED:(id) => `/financial/allocations/${id}/mark-used`,
    ALLOCATION_CANCEL:   (id) => `/financial/allocations/${id}/cancel`,
    ALLOCATIONS_SUMMARY: '/financial/allocations/summary',
  },
};
